#eureka的端口号
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #http://localhost:8888/
      #http://101.43.35.219:8888/
