#注册进eureka
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8888/eureka/
  #配置网关端口号
  server:
    port: 8080
  spring:
    application:
      name: gateway-server
      # redis配置
    redis:
        # Redis数据库索引（默认为0）
      database: 1
        # Redis服务器地址
      host: 101.43.35.219
        # Redis服务器连接端口
      port: 6379
        # Redis服务器连接密码（默认为空）
      password: root
        # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
            # 连接池最大连接数
          max-active: 200
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
            # 连接池中的最大空闲连接
          max-idle: 10
            # 连接池中的最小空闲连接
          min-idle: 0
    cloud:
      gateway:
        routes:
          - id: commodity # 路由的id,没有规定规则但要求唯一,建议配合服务名
            #匹配后提供服务的路由地址
            # 匹配到的以/customer/开头的路径都转发到order的服务
            uri: lb://commodity-mall/
            #          OR uri: http://localhost:8889
            predicates:
              - Path=/commodity/**
            # 去掉匹配到的路径的前2级
            # http://localhost:8080/commodity/t
            filters:
              - StripPrefix=1

          - id: user
            uri: lb://user-server/
            predicates:
              - Path=/user/**
              # http://localhost:8080/user/d
            filters:
              - StripPrefix=1



